# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: ${{ load_from_file("pyproject.toml").project.name }}
  version: ${{ load_from_file("pyproject.toml").project.version }}
  summary: ${{ load_from_file("pyproject.toml").project.description }}
  homepage: ${{ load_from_file("pyproject.toml").project.urls.Source }}
  documentation: ${{ load_from_file("pyproject.toml").project.urls.Documentation }}
  license: ${{ load_from_file("pyproject.toml").project.license.text }}
  build_requires: ${{ load_from_file("pyproject.toml")["build-system"].requires[0] }}
  python_requires: ${{ load_from_file("pyproject.toml")["requires-python"] }}

recipe:
  name: urljsf-split

source:
  path: ../dist/${{ name }}-${{ version }}.tar.gz

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - ${{ name }} = ${{ name }}.cli:main
    requirements:
      host:
        - ${{ build_requires }}
        - pip
        - python ${{ python_requires }}
      run:
        - jinja2
        - jsonschema >=4.18
        - python ${{ python_requires }}
        - tomli
        - typing_extensions >=4.0.0
    tests:
      - python:
          imports:
            - ${{ name }}
      - script:
          - ${{ name }} --version
          - ${{ name }} --help
      - requirements:
          run: [pip]
        script: [pip check]

about:
  homepage: ${{ homepage }}
  license: ${{ license }}
  license_file: LICENSE
  summary: ${{ summary }}
  documentation: ${{ documentation }}
