version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  commands:
    - mamba install -c conda-forge -c nodefaults pixi==0.35.0
    - pixi run build-yarn
    - pixi run build
    - pixi run dist
    - pixi run docs-sphinx
    - pixi run docs-rtd
