version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # `mambaforge-latest` will now start failing: we just need a working `mamba`
    python: mambaforge-23.11
  commands:
    - mamba install -c conda-forge -c nodefaults pixi==0.35.0
    - pixi r build-yarn
    - pixi r build
    - pixi r dist
    - pixi r docs-fetch
    - pixi r docs-pip
    - pixi r docs-sphinx
    - pixi r docs-rtd
