on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const {repo, issue} = context;
            const {number} = issue;
            github.rest.issues.createComment({
              issue_number: number,
              owner: repo.owner,
              repo: repo.repo,
              body: `> View on [ReadTheDocs](https://urljsf--${number}.org.readthedocs.build/en/${number})`
            });
